# Generated by Django 4.1.7 on 2023-02-14 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='g.name', max_length=50, verbose_name='Group name')),
                ('start_date', models.DateField(default=datetime.date(2023, 2, 14))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group_description', models.TextField()),
            ],
        ),
    ]
