# Generated by Django 4.1.7 on 2023-02-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(db_column='f.name', max_length=50, verbose_name='Group name'),
        ),
        migrations.AlterModelTable(
            name='group',
            table='Oxford',
        ),
    ]
