# Generated by Django 4.1.7 on 2023-02-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_group_name_alter_group_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(db_column='g.name', max_length=50, verbose_name='Group name'),
        ),
    ]
